Enabled templated hostfile
CSC-IT-Center-for-Science/ansible-role-hosts-inventory pull request #5
Opened 2017-03-17 13:24 UTC by khappone

Fixed templating options so that templated hostfiles work.

Removed extra debug task from the beginning which I had forgotten there
in another commit.

2017-03-21 12:41 UTC, rlaurika requested changes

2017-03-21 12:41 UTC, rlaurika commented on tasks/template.yml
> +- name: "Build hosts file from defined host data using template"
There should be a "notify" here like in the other two methods to build the hosts file.

2017-03-21 13:58 UTC, khappone commented
Of course. Idiot me. fixed.

2017-03-22 10:57 UTC, rlaurika approved these changes

2017-03-22 10:58 UTC, merged